using NUnit.Framework;
// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace SeleniumTest
{
    [TestFixture]
    //代表包含單元測試的類別
    public class Tests
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void TestLogin()
        {

            driver.Navigate().GoToUrl("https://airdnd-frontend.azurewebsites.net/");
            Thread.Sleep(200);
            driver.FindElement(By.Id("noShowAgainCheckbox")).Click();
            Thread.Sleep(200);
            driver.FindElement(By.Id("close-btn")).Click();
            driver.FindElement(By.CssSelector(".fa-chevron-down")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".btn-outline-light"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            driver.FindElement(By.CssSelector(".btn-outline-light")).Click();
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.Id("check-email")).Click();
            driver.FindElement(By.Id("check-email")).SendKeys("jpy85691@cdfaq.com");
            driver.FindElement(By.Id("continuebtn")).Click();
            driver.FindElement(By.Id("login-password")).Click();
            driver.FindElement(By.Id("login-password")).SendKeys("123456");
            driver.FindElement(By.Id("loginbtn")).Click();
            //延遲一下，才找的到節點
            Thread.Sleep(200);
            driver.FindElement(By.CssSelector(".dropdownbox")).Click();
            driver.FindElement(By.LinkText("帳號")).Click();
            driver.FindElement(By.CssSelector(".Name")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".Name")).Text, Is.EqualTo("周杰倫 ,"));
        }

    }
}